# Generated by Django 5.1 on 2024-08-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0006_watchlist_avg_rating_watchlist_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='rating',
            new_name='number_ratings',
        ),
    ]
